---
version: 2.1

orbs:
  rust: brownjohnf/rust@volatile

workflows:
  default:
    jobs:
      - rust/build:
          name: build_debug
          version: latest
      - rust/test:
          version: latest
          requires:
            - build_debug
      - rust/build:
          name: build_release
          version: latest
          release: true
          requires:
            - rust/test

